name: jupyterlab-ros
channels:
- conda-forge
- robostack
dependencies:
- nodejs=10
- jupyterlab
- ros-melodic-ros-core
- ros-melodic-rospy
- ros-melodic-rosbridge-suite
- ros-melodic-rosbag
- ros-melodic-rosauth